# SPDX-License-Identifier: GPL-2.0
#
# USB Raw Gadget
#

ccflags-y			:= -I$(srctree)/drivers/usb/gadget/
ccflags-y			+= -I$(srctree)/drivers/usb/gadget/udc/
ccflags-y			+= -I$(srctree)/drivers/usb/gadget/function/

obj-$(CONFIG_USB_RAW_GADGET)	+= raw.o
